---
- name: collect information
  hosts: all
  gather_facts: no
  vars_files:
   - /docker-data/ansible/external_vars.yml

  tasks:
  - name: Preventive Maintenance
    ios_command:
     commands:
      - show version
      - show ip interface brief
      - show inventory
      - show run
    register: switch_config

  - name: save collected infromation in data directory
    copy:
     dest: "/docker-data/ansible/PM.txt"
     content: |
        show version
        ------------
        {{ switch_config.stdout[0] }}
        show ip interface brief
        --------------------
        {{ switch_config.stdout[1] }}
        show inventory
        --------------
        {{ switch_config.stdout[2] }}
        show run
        --------
        {{ switch_config.stdout[3] }}
